### ISSUE TITLE
=?utf-8?Q??= as address.name

### ISSUE THREAD

**Issue by Sjonnie2nd** [andris9/mailparser#126]
Two times I've seen raw emails with to: =?utf-8?Q??= <...right@address...>.
They got parsed as .to: [{ address: "right@address", name:"=?utf-8?Q??=" }].
The sender(app) is wrong here in sending an encoded empty string but..
Shouldn't it be parsed as .to: [{ address: "right@address" }]. That is: ignoring the name?

**Comment by andris9** [comment]
rfc2047 states the following for the encoded text part:

```
encoded-text = 1*<Any printable ASCII character other than "?"
               or SPACE>
```

that means that there must be at least 1 character between the ? symbols, otherwise the construct is not valid mime encoded word, so if this construct is not converted then it is not a bug.

Anyway, could you provide a working example for this behavior as I do not seem to be able to properly reproduce it myself, `=?utf-8?Q??=` gets converted to empty string as expected.

**Comment by Sjonnie2nd** [comment]
Hello Andris,

I also tried to reproduce it but you are right: name = "".

About a year ago i received those emails and using mailParser I then got name: "=?utf-8?Q??=".
I kept them in my todolist and I just recently picked it up.
Seems that it (if there has been an issue) already was resolved.

I'm sorry for the inconvenience.
